function active_perm = InverseMaxwellGarnett(eff_perm, med_perm, active_volume)

active_perm = med_perm.*(2*med_perm*active_volume + active_volume*eff_perm...
    -2*med_perm+2*eff_perm)./(2*med_perm*active_volume + active_volume*eff_perm...
    + med_perm - eff_perm);
end